### ISSUE TITLE
Error running the adapted kubectl service

### ISSUE THREAD

**Issue by Minninnewah** [SSU-DCN/podmigration-operator#11]
Hi
I'm trying to set up the environment accordingly to your steps. Unfortunately, there is an error reloading the kubelet service:
![grafik](https://user-images.githubusercontent.com/40040609/199679162-60b57cda-ea4d-44be-9783-23038dfa1248.png)
 
![grafik](https://user-images.githubusercontent.com/40040609/199679236-126a110a-0545-4be2-9710-8e9377294acf.png)
The log from "journalctl -xf -u kubelet" shows that there is no config file for kubelet. Since this problem is often solved by running the "kubeadm init" commands I also tried this which also results in an error that kubelet is not running.
![grafik](https://user-images.githubusercontent.com/40040609/199681453-bddb4336-e15b-4fa8-ad65-9edbe2753472.png)
After this command the "journalctl -xf -u kubelet" output changed, obviously it's now missing docker that should not be used in the first place.
 
 
Deviations from the steps described by you:
- Before "sudo make install" of the https://github.com/vutuong/containerd-cri.git I had to install the newest version of goLang because of some missing files -> changed it back to the specific version after this command.
- For step 5 I used the commands listed below (I'm not sure if I should move the binaries somewhere else since they are mentioned)
- Additionally, in step 5 different to the command in the video I used "make" since "make quick-release" result in an error on the RUN layers in the Dockerfile (ttrpc: closed: unknown) that perhaps indicate that something is wrong with the containerd-cri
 
For step 5 I used the following commands:
cd containerd #in tpm
 
// Get kubernetes source code
git clone https://github.com/vutuong/kubernetes.git
 
// Add kubernetes source code to GOPATH
git clone https://github.com/vutuong/kubernetes.git $GOPATH/src/k8s.io/kubernetes
cd $GOPATH/src/k8s.io/kubernetes
hack/install-etcd.sh
export KUBERNETES_PROVIDER=local # errors
 
// old golang version  from step 1 which is needed for the make command
sudo apt-get --purge remove golang-go -y
cd $HOME/tmp
sudo tar -xzf go1.15.5.linux-amd64.tar.gz
sudo rm -rf /usr/local/go
sudo mv go /usr/local
cd $GOPATH/src/k8s.io/kubernetes
 
make

Do you have any hints about this error?
All the used commands can be found at https://github.com/Minninnewah/MiCoMTD/blob/main/testbed/setup_environment.sh.

**Comment by Minninnewah** [comment]
Adding the containerd.sock path in the kubeadm command results in a different error and again it looks like the kubelet is the problem.
![grafik](https://user-images.githubusercontent.com/40040609/199783845-73c605fc-1f43-47f8-a7f5-0bda30b63e43.png)


journalctl -xeu kubelet
![grafik](https://user-images.githubusercontent.com/40040609/199783562-ca51a2ac-d4f9-42db-bf90-816ae65ce137.png)

**Comment by vutuong** [comment]
hi @Minninnewah,
Firstly, I notice from the log that it should have docker running in your host, right ? Please notice that in this PoC, we did not using docker as container runtime for K8s but containerd. So please remove docker from your host first.

Secondly, as in the step ```Step1: Install container runtime - Containerd```, we offer two way to achieve containerd-cri ( extended) as ```1. Build from source:``` or  ```2. Download binaries ```. You have to select only one option not both. Since may be you got error when building the code by yourself. I suggest that you should use our binary 
 in ```binaries.tar.bz2```
P/s: This PoC a litle bit old and may not catchup with newest version of K8s components. At the time, we are using ```kubeadm=1.19.0-00 kubelet=1.19.0-00 kubectl=1.19.0-00```, ```v1.0.0-rc92/runc.amd64```

**Comment by Minninnewah** [comment]
Hi @vutuong 
The problem with the docker occurred in step 7 at the kubadm command and there was no such error in the build command of the containerd-cri. Furthermore, I think the kubeadm command tried to use docker because some files remained after uninstall. But fortunately, I can circumvent this problem using the direct path to the containerd.sock as mentioned in the second post. Nevertheless, I also tried to use the precompiled binaries which didn't change anything.

**Comment by vutuong** [comment]
Hi @Minninnewah,
Did you follow the guide at the multi-cluster branch ?
It maybe missing the step 7 in comparison with the main branch.
https://github.com/SSU-DCN/podmigration-operator/blob/main/init-cluster-containerd-CRIU.md
```
$ sudo nano /var/lib/kubelet/config.yaml

authorization:
  #mode: Webhook
  mode: AlwaysAllow
```

**Comment by Minninnewah** [comment]
Hi @vutuong 
I'm using the main branch to set up this first environment.
The config.yaml is overwritten in the "kubeadm init" command and therefore, I cannot change the mode, I think that's probably important for the other commands afterwards.
I also checked the kubeadm daemon and tried to run the kubelete command that is used by kubeadm:
![grafik](https://user-images.githubusercontent.com/40040609/200320356-19a4f2a3-56e3-4b8f-812f-33411f8f56d9.png)
And it looks like kubelet has some connection problem.
![grafik](https://user-images.githubusercontent.com/40040609/200320537-3d160dfd-7d1c-497b-8b2d-910a444cbd39.png)
Do you think this is an error somewhere in the kubelet part or is it more likely in the runtime part?
The complete log of this command is attached.
[log.txt](https://github.com/SSU-DCN/podmigration-operator/files/9951957/log.txt)

**Comment by vutuong** [comment]
Hi @Minninnewah,
Could you please try to replace your step 5, 6 with:
``````
git clone https://github.com/SSU-DCN/podmigration-operator.git
cd podmigration-operator
tar -vxf binaries.tar.bz2
cd custom-binaries

chmod +x kubeadm kubelet
sudo mv kubeadm kubelet /usr/bin/
sudo systemctl daemon-reload
sudo systemctl restart kubelet
sudo systemctl status kubelet
```
That try to use our already built binaries. After that please give me the log from ```systemctl -xf -u kubelet```.

**Comment by Minninnewah** [comment]
Hi @vutuong 
These commands are exactly the same as in your instructions step 6 that I already used. So do you mean I should just skip step 5?
I follow these instructions:
https://github.com/SSU-DCN/podmigration-operator/blob/main/init-cluster-containerd-CRIU.md

**Comment by vutuong** [comment]
@Minninnewah,
Yep, you should skip this step but you still need to do ```git clone https://github.com/vutuong/kubernetes.git``` because when you run the podmigration controller it use some lib in this repo.
It maybe my labmate's mistake when he updated the doc since he separate it into 2 steps. I gonna fix this confuse.

FYI: You don't need to build the kubelet extended version by yourself as step 5 because we already built it for you and put it in the ```binaries.tar.bz2`` folder.
Do step 6 to extract to get the extended kubelet and kubeadm binaries and replace it with the k8s default binaries. 
Good luck ~!

**Comment by Minninnewah** [comment]
Thank you now it's less confusing to me.
Does it matter where I clone the repository (as an example also in "tmp" folder) since I don't see how these libs are found since there is no path that has to be set?

**Comment by vutuong** [comment]
Hi @Minninnewah,
Checking the go.mod file, you will see that ```https://github.com/SSU-DCN/podmigration-operator/blob/main/go.mod```
```
replace k8s.io/api => ../kubernetes/staging/src/k8s.io/api
replace k8s.io/apimachinery => ../kubernetes/staging/src/k8s.io/apimachinery
replace k8s.io/client-go => ../kubernetes/staging/src/k8s.io/client-go
```
So you should download it to the same directory as you store the ```podmigration-operator```. For example:
```
/tmp
├── your_directory
│   ├── kubernetes
│   ├── podmigration-operator
```

**Comment by Minninnewah** [comment]
Hi @vutuong 
[Logs](https://github.com/SSU-DCN/podmigration-operator/files/9961102/log2.txt) from running "journalctl -xf -u kubelet" before the "kubadm init" command:
-> error about missing config file

[Logs](https://github.com/SSU-DCN/podmigration-operator/files/9961103/log3.txt) from running after the "kubadm init" command:
-> unable to find data in memory cache

If you have your own VM available you can also run the same commands using
```wget -O - https://raw.githubusercontent.com/Minninnewah/MiCoMTD/main/testbed/setup_environment.sh | bash```

**Comment by vutuong** [comment]
hi @Minninnewah 
Did you try this ? https://github.com/opsnull/follow-me-install-kubernetes-cluster/issues/620
I've never see that error before. Did you try to run ```swap off -a``` and ```kubeadm reset -f``` before run the ```kubeadm init``` again ?
I'm not sure that the command you used to remove docker can remove docker completely or not. If not try to make the clean your environment by reinstall OS.  
P/S: One more point, Could you please skip this step.
```
$ sudo nano /var/lib/kubelet/config.yaml

authorization:
  #mode: Webhook
  mode: AlwaysAllow
  ```
  Please do it after you run ```kubeadm init``` without error and restart kubelet.

**Comment by Minninnewah** [comment]
Hi @vutuong 

Finally, it works (I didn't check the video stream with vlc yet but at least the containers are running also after the migration, checking with kubectl). The error was somewhere in the Ubuntu image that I used because the errors are gone after setting up the VM with a new image.

I have a few additional questions about a few parts of the software:
- Is it correct that the API server as well as the Podmigrator-Operator are console-blocking requests if just executed as described in this repository?
- Furthermore, do I understand it correctly that the API server as well as the Podmigrator-Operator only has to be run on the master node? I got errors if I try it on the worker nodes.
- Is it normal that kubectl commands fail on the worker node (The connection to the server localhost:8080 was refused - did you specify the right host or port?)
- Probably there is no easy way to keep the name of the pod through the migration because of Kubernetes is that correct?

**Comment by vutuong** [comment]
Hi @Minninnewah,
1. Is it correct that the API server as well as the Podmigrator-Operator are console-blocking requests if just executed as described in this repository?
 - For easily debug we just run them as command in terminal. But you can use kubebuilder to make the controller run as a pod in the cluster. We also can run the api-server as a service or pod.
 2. Furthermore, do I understand it correctly that the API server as well as the Podmigrator-Operator only has to be run on the master node? I got errors if I try it on the worker nodes.
 - Yes, in the context of this PoC. Podmigrator-Operator include a controller as other default k8s controller and should be placed in a controller plane, I mean master nodes. Our api-server is a translator of K8s api-server so it should be placed beside k8s api-server. We follow the basic setup of k8s cluster when k8s controller and api server placed only in master node.
3. Is it normal that kubectl commands fail on the worker node (The connection to the server localhost:8080 was refused - did you specify the right host or port?)
- Definitely, yes. Kubectl have to use kube config file to request and receive response the info from k8s api-server. If you want to run the kubectl on the worker node, you have to copy the ```~/.kube/config``` from the master node to worker node. Please check: https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/ 
4. Probably there is no easy way to keep the name of the pod through the migration because of Kubernetes is that correct?
- No. if you migrate pod in single cluster, you can not keep the name of pod. Because K8s default does not allow to create 2 pods with the same name. We keep the source pod until the destination pod create and restore, therefore, source pod and dest pod can not have same name.
- Yes, if you migrate pod to another cluster, you can keep the name of pod because they are not on the same cluster. But in the Poc, we randomly generate the pod name.
- You can notice that the k8s deployment auto generate pod-name, it does not keep the pod name when recreate it.
