### ISSUE TITLE
Failed to migrate pod and run Podmigration operator

### ISSUE THREAD

**Issue by Hebert007306** [SSU-DCN/podmigration-operator#14]
Hi @vutuong, 
I tried to use your method to build the cluster without any other modifications, and deploy kubernetes and podmigration-operator in 3 nodes: controller, node1, node2. But when I tried to run the migration steps between node1 and node2, the migration was always unsuccessful, and the error log is as follows
![image](https://user-images.githubusercontent.com/77536603/209556157-183ed4f2-414c-459d-ae36-0cded6f887a5.png)
![image](https://user-images.githubusercontent.com/77536603/209556186-282779f3-2e72-40e9-b1a1-2f5d70481619.png)
The cluster built according to your method is working normally, and the environment is ubuntu 18.04.
![image](https://user-images.githubusercontent.com/77536603/209556267-07ddab80-056c-46e7-9885-890203c3cd97.png)
![image](https://user-images.githubusercontent.com/77536603/209556333-27a317e8-ee2d-4a64-9447-256081fe478e.png)

These problems have troubled me for a long time, so I'm sorry to disturb you . I'm looking forward to your reply. Merry Christmas，thanks a lot!

**Comment by vutuong** [comment]
@Hebert007306 
Firstly, thank you for using our repo.
I see in the controller log that it stuck in the step 3. As in my code, I have a forever loop will wait for the checkpoint info is completely created at ```/var/lib/kubelet/migration/kkk```. So I guess that something happen that make CRIU can not checkpoint the pod. Could you please check if any data are created into   ```/var/lib/kubelet/migration/kkk``` ? And please make sure that the Step 9 should be right configured and tested.
This data stored the checkpointed info and  must be created then share with the destination node to restore the pod at the destination node. 
Please recheck and show the log about CRIU version. 
This guy made the bash script to install it from my guide and support. https://gitlab.com/mindhappyokk/pod-migrating
Maybe it can help you to avoid some error from manually installation.

**Comment by Hebert007306** [comment]
Hi @vutuong,
I’m really grateful for your kind sharing! What you have done is really meaningful!
After a few experiments, I finally completed pod migration both from node to node in single cluster and from cluster to cluster. However, there are still some questions which is vague to me. Could you take a look at them when you have time? Thank you in advance!

1.How to solve the contradiction between the Kubernetes system and Pod migration, especially between Pod uniqueness and migration, such as Pod identifiers and IP conflicts caused by migration? Kubernetes organize and manage the container with Pods that have a single assigned mark in Kubernetes. As a basic deployment unit, Pods have unique identifiers and IP. Pods migration can be considered as the rebirth of a Pod in a different place, and the new Pod should be completely consistent with the source Pod. Therefore, there is a contradiction between Pod uniqueness and migration, while the IP management system does not allow address conflicts. So how does this project carry out Pod identification and IP address management?

2.This experiment modifies some components of Kubernetes and the container runtime interface CRI, coupling it with CRIU, which provides a complete and reliable migration mechanism for the container runtime RunC at the execution level. May I ask which parts have been specifically modified? Or is there any relevant research materials that I can refer to?

3.At present, K8s mainly promotes the expansion and contraction of stateless containers. The expansion and contraction process in the K8s ecosystem directly conflicts with the migration process. How did you solve it?

4.What is the method you applied when cleaning up the source Pods in this project?

5.It is noticed that, when the pod is migrated, the pod IP and name have changed before and after the migration. During the cross-cluster pod migration, the server address and port (192.168.10.1:XXXX) of the service have also changed. Is there anay method to avoid the constant delay the users feel while watching videos and thus achieving better user experience? For now, if users want to watch videos, they feel the delay caused by the pod migration or the migration interruption time. After the migration, the user need to open another vlc window and enter the address and port (192.168.10.2:XXXX) again to play the video. Is there any way to avoid the inconvenience?
My idea is to make a DNAT address translation in the source cluster (cluster1) after the pod migration is completed. As a result, when the pod service is migrated from cluster1node1 to cluster2node1, the user will send the access flow while the target address is still cluster1 regardless of the migration. Through DNAT in cluster1, the target address is directly changed to the service IP of cluster2, and the data flow is forwarded from cluster1 to cluster2. In the end, we could access the migrated Pod service in cluster2node1.

Finally, I would greatly appreciate it if you could recommend any paper or online materials relevant to this project. Thanks for your time! Looking forward to your reply!

**Comment by vutuong** [comment]
Hi @Hebert007306,
I'm really happy to hear that you succeed to install and run the demo.
It's a year from the time I made this PoC. At this time I need to read the kubelet source code to understand what exactly kubelet did. I'm now not remeber all the things but this is my answer for your question:

1. Some code was added to the kubelet to make the kubelet trigger the checkpoint and restore method of containerd. And some code is also added to containerd CRI to listen that trigger. The communication between kubelet and containerd is based on GRPC protocol so you should read about GRPC to understand. This project did not care about the IP address of the pod, because the totally new pod is create at the destination node. But the start method of kubelet and containerd CRI were changed to not start as normal but start with checkpoint info. I recommend you to read the thesis from here to understand more information. https://www.researchgate.net/publication/349662156_Migrating_Pods_in_Kubernetes The idea of making the pod migration initially come from this guy. I've just modified some to match with our paper, separated checkpoint and restore process to make it run with mutli-cluster and made the document for installation.
2. The ref as I mention : https://www.researchgate.net/publication/349662156_Migrating_Pods_in_Kubernetes
3. Same as question 2
4. I made the pod-migration controller that takes care of migrating process since it will trigger kubelet at source node to delete old pod when the new pod was restored success at dest node.
5. You can use the concept of haproxy to make it ease. My setting is describe in our paper : https://ieeexplore.ieee.org/document/9903004
