### ISSUE TITLE
Which part of code fixed？

### ISSUE THREAD

**Issue by 120L020314** [SSU-DCN/podmigration-operator#19]
Sorry to disturb,but it's very important for me.Just a few days ago,i have run your code in my vmare virtual machine cluster successfully.And the main area i research is the pod migration in K8s.Your work gives me a very good example to achieve that.i don't have any experience to do that,so it's a little hard for me to understand your fix on K8s,so can you guide me where part of the code , i should study which you fixed based on K8s.i can't find where is fixed or different from the source code of K8s.Can you point out which files i should look helps me understand your work?Thank you very much!

**Comment by 120L020314** [comment]
https://github.com/vutuong/kubernetes.git，like this project，which files should i study that you fixed from the source code from K8s.i can not know where is the code your work does.thank you!  @vutuong

**Comment by vutuong** [comment]
@120L020314 simplely check the commits history at that repo. If you are using git. you should know how to check it.

**Comment by 120L020314** [comment]
@vutuong i will try ,thank you very much!

**Comment by 120L020314** [comment]
Sorry to disturb，Do you have any related papers introducing the implementation of this system? It ’s a little hard for me to understand，thank you very much！ @vutuong

**Comment by vutuong** [comment]
I don't have any documentation providing detailed code guidance. My documentation primarily focuses on presenting ideas and designs rather than detailed implementation instructions. However, my approach is influenced by the work of the individual mentioned in the following link: https://www.researchgate.net/publication/349662156_Migrating_Pods_in_Kubernetes. This individual has published a comprehensive master's thesis that delves into various aspects of the topic. I recommend exploring this thesis for detailed code guidance. Specifically, it may be beneficial to investigate how the kubelet operates within the Kubernetes architecture, how to install Kubernetes using binary files, and how to replace existing binaries with custom ones. Additionally, understanding the functionality of Kubernetes operators could provide valuable insights.

P/S: This space is reserved for repository issues. Please refrain from asking questions here. If you have any inquiries, feel free to reach out to me via email. You can find my personal email in my profile.
